filter:
    excluded_paths: [vendor/*, config/*]

checks:
    php:
        code_rating: true
        duplication: true

build:
    tests:
        override:
            -
                coverage:
                    file: 'clover.xml'
                    format: 'php-clover'
