filter:
    excluded_paths: [vendor/*, config/*]

checks:
    php:
        code_rating: true
        duplication: true

build:
    tests:
        override:
            -
                command: 'phpunit --coverage-clover=clover.xml ./test/'
                coverage:
                    file: 'clover.xml'
                    format: 'php-clover'
